"""Vision perception and spatial grounding (Law 1, ADR-2)."""

from computeruse.vision.ax import (
    AXElement,
    element_rect,
    element_summary,
    find_elements,
    focused_text_value,
    interactive_summaries,
)
from computeruse.vision.capture import (
    LumaGrid,
    ScreenCapture,
    to_luma_grid,
    verify_capture_region,
)
from computeruse.vision.coordinates import (
    CoordinateOutOfBoundsError,
    DisplayGeometry,
    Point,
    Rect,
    Size,
    display_origin_offset,
    display_px_to_global_point,
    global_point_to_display_px,
    pixels_to_point,
    point_in_frame,
    point_to_pixels,
    point_to_screenshot_offset,
    scale_point,
)
from computeruse.vision.diff import (
    ChangeKind,
    ChangeVerdict,
    Verification,
    crop_luma,
    downsample_luma,
    regional_diff,
    regional_mean_abs,
    to_luma,
    verdict,
)
from computeruse.vision.focus import FocusedWindow, window_summary

__all__ = [
    "AXElement",
    "ChangeKind",
    "ChangeVerdict",
    "CoordinateOutOfBoundsError",
    "DisplayGeometry",
    "FocusedWindow",
    "LumaGrid",
    "Point",
    "Rect",
    "ScreenCapture",
    "Size",
    "Verification",
    "crop_luma",
    "display_origin_offset",
    "display_px_to_global_point",
    "downsample_luma",
    "element_rect",
    "element_summary",
    "find_elements",
    "focused_text_value",
    "global_point_to_display_px",
    "interactive_summaries",
    "pixels_to_point",
    "point_in_frame",
    "point_to_pixels",
    "point_to_screenshot_offset",
    "regional_diff",
    "regional_mean_abs",
    "scale_point",
    "to_luma",
    "to_luma_grid",
    "verdict",
    "verify_capture_region",
    "window_summary",
]
